### ISSUE TITLE
The number of genes in the result file was not consistent with the total number of species gene sets

### ISSUE THREAD

**Issue by shaos1996** [qiao-xin/DupGen_finder#10]
Hello, I used the sample file in the data folder to test the program dupgene_finder-unique. The number of genes is less than the total number of genes in Arabidopsis. Did I do anything wrong? Here's what I got for Arabidopsis.

  113 Ath.singletons
  3697 Ath.dispersed.genes-unique
  1056 Ath.proximal.genes-unique
  2890 Ath.tandem.genes-unique
  4317 Ath.transposed.genes-unique
  7545 Ath.wgd.genes-unique

**Comment by qiao-xin** [comment]
After removing WGD, tandem, proximal, and transposed duplications from the whole set of homologous gene pairs (or BLASTP hits), the remaining gene pairs were classified as dispersed duplications. However, when identifying dispersed gene pairs, the same gene may have several BLASTP hits resulting in multiple gene pairs for this gene, we only considered the dispersed gene pairs with highest similarity in this situation. For example, 

query gene ID	subject gene ID	...	e-value
gene A	gene B	...	5e-52
gene A	gene C	...	3e-45
gene A	gene D	...	6e-126
gene A	gene E	...	3e-30
...

In above case, the pairs gene A-gene B, gene A-gene C, and gene A-gene E will be discarded, and the best hit gene A-gene D will be reserved and outputted into the result file ‘Xxx.dispersed.pairs’ (e.g. Ath.dispersed.pairs). This may be resulted in that gene B, C, or E are neither classified into duplicated genes nor singletons. Therefore, not all the genes in the GFF file can be found in the final outputs (xxx.pairs and xxx.singletons).

**Comment by jwli-code** [comment]
Hello, I would like to ask whether these unassigned genes can be manually categorized as dispersed pairs, or if they should be considered as not belonging to any type of duplication. @qiao-xin
