### ISSUE TITLE
Add document about how to use DupGen_finder without out group species.

### ISSUE THREAD

**Issue by xiekunwhy** [qiao-xin/DupGen_finder#12]
Hi,

I have only one species and want to find DepGen using itself, but I can not found any document about how to do that, and I got errors when I using itself as target and outgroup species.
cp input/Pca.blast input/Pca_Pca.blast
cp input/Pca.gff input/Pca_Pca.gff

ls input|cat
Pca.blast
Pca.gff
Pca_Pca.blast
Pca_Pca.gff

perl /Bio/software/DupGen_finder/DupGen_finder.pl -i /state/partition1/WORK/DupGen_finder/input -t Pca -c Pca -o /state/partition1/WORK/DupGen_finder/output/
rm: cannot remove `/state/partition1/WORK/DupGen_finder/output/Pca_Pca.gff.sorted': No such file or directory

And I got nothing!

Best,
Kun

**Comment by qiao-xin** [comment]
The problem was not caused by the use of outgroup species. Please refer to the #7

**Comment by xiekunwhy** [comment]
Hi,

Thank you for your reply, it works.

Best,
Kun
