### ISSUE TITLE
ancestral and novel transposed duplications

### ISSUE THREAD

**Issue by cwb14** [qiao-xin/DupGen_finder#14]
Hello,

In the `species.transposed.pairs` file, is column 1 (`"Duplicate 1"`) the ancestral copy and column 3 (`"Duplicate 2"`) the non-ancestral copy? Or are ancestral and non ancestral pairs shuffled between column 1 and column 3 and I need to run OrthoFinder to determine which is ancestral?

Thank you,
Chris

**Comment by qiao-xin** [comment]
Genes contained in column 1 are the transposed copies and genes column 3 represent the parental loci.

**Comment by cwb14** [comment]
Great! Thank you for the quick feedback.
