### ISSUE TITLE
"*.gff.sorted". No such file or directory

### ISSUE THREAD

**Issue by Dayana-Turquetti** [qiao-xin/DupGen_finder#20]
Hi! 
I am trying to use DupGen_finder.pl, but there is some error.

# I am using in command line:
perl DupGen_finder.pl -i /media/dragonstone/dayana/KaKs/data_dir/ -t gma -c pvu -o /media/dragonstone/dayana/KaKs/results

# error
rm: cannot remove '/media/dragonstone/dayana/KaKs/results/gma_pvu.gff.sorted': No such file or directory
Is this file "*.gff.sorted" not being created?
Thanks if you can help me.

Dayana. 

---
# Content of my data_dir:
gma.blast
gma.gff
gma_pvu.blast
gma_pvu.gff

**Comment by Dayana-Turquetti** [comment]
I found the trouble!

**Comment by kamalmdmostafa** [comment]
> I found the trouble!
Hi Dayana, 
How did you solve the issue? I am also seeing the same issue!

**Comment by kamalmdmostafa** [comment]
> I found the trouble!

Hi Dayana,
How did you solve the issue? I am also seeing the same issue!

**Comment by Dayana-Turquetti** [comment]
Hi, Kamal! 

Have you checked if the input files are in accordance with the tutorial? My error occurred in the .gff file. 
I was using a file with redundancies, and moreover, there was an error in the gene names as well. Below, I will send an example of the files in my directory. I worked with soybean (gma) and common bean (pvu). I hope this helps you!

gma.gff
gma-Chr01	Glyma.01G000100	27344	28430
gma-Chr01	Glyma.01G000137	52485	52601

gma_pvu.gff
pvu-Chr01	Phvul.001G000400	706	6715
pvu-Chr01	Phvul.001G000500	10461	12321
gma-Chr01	Glyma.01G000100	27344	28430
gma-Chr01	Glyma.01G000137	52485	52601

gma.blast
Glyma.01G000100	Glyma.01G000100	100	104	0	0	1	104	1	104	3.27e-73	212
Glyma.01G000100	Glyma.15G276800	77.5	111	3	1	1	89	924	1034	2.74e-48	164

gma_pvu.blast
Phvul.L001612	Glyma.13G010700	85.3	307	44	1	1	307	734	1039	4.3e-149	525.4
Phvul.010G034400	Glyma.03G093600	86.1	509	65	4	3	506	2	509	2.5e-255	879.0

**Comment by kamalmdmostafa** [comment]
Hi Dayana, 
Yes, the gff files were according to the tutorial. 

I got frustrated with MCScanX, so I deleted it from the server and removed it from all paths. It worked. But still, I am having issues when I run it without an outgroup.  

Thank you!

**Comment by Ting-Fang** [comment]
I also encountered the same problem. When I run the example: "DupGen_finder-unique.pl -i data -t Ath -c Nnu -o results", it occurs "rm: cannot remove 'results/Ath_Nnu.gff.sorted': No such file or directory".

**Comment by LiCongcong0707** [comment]
(family_analysis) t110626@staru04-server:~/cyp/dup_working$ head -3 AvaHapA.gff
AvaHapA-Chr01A  Av_01Ag000001.mRNA1     8876    9460
AvaHapA-Chr01A  Av_01Ag000002.mRNA1     14322   15447
AvaHapA-Chr01A  Av_01Ag000003.mRNA1     19236   20047
(family_analysis) t110626@staru04-server:~/cyp/dup_working$ head -3 AvaHapA_grape.gff
AvaHapA-Chr01A  Av_01Ag000001.mRNA1     8876    9460
AvaHapA-Chr01A  Av_01Ag000002.mRNA1     14322   15447
AvaHapA-Chr01A  Av_01Ag000003.mRNA1     19236   20047
(family_analysis) t110626@staru04-server:~/cyp/dup_working$ tail -3 AvaHapA_grape.gff
grape-chr19     Vitvi05_01chr19g23110_t001      27143114        27147131
grape-chr19     Vitvi05_01chr19g23120_t001      27151491        27151772
grape-chr19     Vitvi05_01chr19g23130_t001      27201958        27202330
(family_analysis) t110626@staru04-server:~/cyp/dup_working$ perl ~/DupGen_finder-1.0.0/DupGen_finder-unique.pl -i ~/cyp/dup_working/ -t AvaHapA -c grape -o ~/cyp/dupgen_out/Ava.hapA
rm: cannot remove '/home/data/t110626/cyp/dupgen_out/Ava.hapA/AvaHapA_grape.gff.sorted': No such file or directory

 files are in accordance with the tutorial,but still encountered the same problem

**Comment by qiao-xin** [comment]
Please check whether the MCScanX algorithm included in DupGen_finder folder rather than the default MCScanX in your system has been invoked successfully.

**Comment by LiCongcong0707** [comment]
Thank you for your reply and suggestion. I have checked the MCScanX
algorithm in the DupGen_finder folder and confirmed that it has been
successfully called. The analysis for this part has been completed. Thank
you for your help.
