### ISSUE TITLE
how to use Ath.wgd.pairs ?

### ISSUE THREAD

**Issue by zhangjinpengGithub** [qiao-xin/DupGen_finder#6]
Dear  Qiao Xin,
    Many thanks for your software,I wonder if it is possible to extract the WGD gene pair for both species from the Ath.wgd.pairs? in other words, we can be sure that it is these gene pairs that produce WGD , And then use gene pairs to analyze.

**Comment by qiao-xin** [comment]
Hi Zhangjinpeng,

The 'Ath.wgd.pairs' includes the duplicated gene pairs (or syntenic gene pairs) derived from WGD events. The gene pairs contained in the file 'Ath.wgd.pairs' is same to the results identified by [MCScanX](http://chibba.pgml.uga.edu/mcscan2/) software.

Good luck!

**Comment by zhangjinpengGithub** [comment]
Dear Qiao Xin,
thanks for your reply. I recently encountered a problem in studying the WGD event: how do I extract the duplicate gene from the WGD  event?  such as "Ath.wgd.pairs“:
Duplicate 1     Location        Duplicate 2     Location        E-value
AT1G17240.1     Ath-Chr1:5896416        AT1G72300.1     Ath-Chr1:27217477       0.0
AT1G17290.1     Ath-Chr1:5922630        AT1G72330.3     Ath-Chr1:27233475       0.0

I want to know if these genes pairs (AT1G17240.1  AT1G72300.1 )are duplicates of genes that are caused by WGD event.
Thank you !

**Comment by qiao-xin** [comment]
Yes, gene pairs (Column 1 and Column 3) contained in the file "Ath.wgd.pairs" are originated from WGD events. You may need to write custom script to extract gene pairs from the file "Ath.wgd.pairs". I hope this will help.

**Comment by zhangjinpengGithub** [comment]
Thanks again and happy New Year to you!

**Comment by Mr-Inamn** [comment]
Dear Qiao Xin,
Many thanks for your software, it is easy to use. I wonder if it is possible to get the gene duplicated families with your software, but not the pairs.

**Comment by qiao-xin** [comment]
Hi Mr-Inamn,

DupGen_finder was designed to identify different types of paralogous gene pairs, and cannot be used to identify a gene family. You can use [HMMER](http://hmmer.org) or [DIAMOND](http://www.diamondsearch.org/index.php) software to identify a list of homologous genes contained in a gene family.

**Comment by Mr-Inamn** [comment]
Dear Qiao Xin,
Thanks for your quick response and help. I will try HMMER, DIAMOND and orthoMCL in my case. 
Good luck.
