### ISSUE TITLE
error when running script

### ISSUE THREAD

**Issue by michaeldnowak** [qiao-xin/DupGen_finder#7]
Hi, thanks so much for building this software, very helpful. 
I am running into the following error when running the script. See below:

-bash-4.1$ ./DupGen_finder.pl -i Dniv_Aalp_Data/ -t Dniv -c Aalp -o /usit/abel/u1/michaeno/nobackup/program_dirs/DupGen_finder/Dniv_Results_13Jan2020
rm: cannot remove `/usit/abel/u1/michaeno/nobackup/program_dirs/DupGen_finder/Dniv_Results_13Jan2020/Dniv_Aalp.gff.sorted': No such file or directory

Any idea why this is occurring?
I notice that a previous version of this script did not have this problem.
Thanks!

**Comment by qiao-xin** [comment]
Hi Michael Nowak,

If you have ever installed [MCScanX](http://chibba.pgml.uga.edu/mcscan2/) software before installing DupGen_finder on your system, please set `PATH` to avoid the conflict between MCScanX software and the custom MCScanX algorithm implemented in DupGen_finder.

Please run the following command to set `PATH` to invoke the custom MCScanX algorithm incorporated in DupGen_finder software.

```
export PATH=~/software/DupGen_finder:$PATH
```

Replace `~/software/DupGen_finder` with the actual path of your installed DupGen_finder. To avoid setting PATH everytime, please insert the export command in your `.bashrc` or `.bash_profile`.

**Comment by michaeldnowak** [comment]
Thanks a lot, that was a rather simple fix! I hadn't previously installed MCScanX on this system before, but the MCScanX distributed with DupGen_Finder indeed needed to be in the path. 
Great tool, thanks again for making it available!
